### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by mlondon88** [littlebrighter/alfred--ultimate-currency-converter#5]
Hi,
I am unable to get this to work.
I installed v1.12.2
I have python v3.10.4
Alfred version 4.6.4
I obtained API and added to workflow environment variable.
However, when I type currency and press spacebar, it asks if I want to search for currency in Google/Amazon, etc
Please advise

**Comment by dexamenos** [comment]
see https://www.alfredforum.com/topic/16732-ultimate-currency-converter/?do=findComment&comment=94781
