### ISSUE TITLE
invalid_access_key error 

### ISSUE THREAD

**Issue by League2EB** [littlebrighter/alfred--ultimate-currency-converter#8]
HI thx all you create this workflow , but i got some error messeage

like that 

```
(
    [error] => Array
        (
            [code] => invalid_access_key
            [message] => You have not supplied a valid API Access Key.
        )

)
```

i choes the service  and input the key  like that, how can i fix it ?

thx all ! 

![image](https://user-images.githubusercontent.com/24560428/207290799-ffb24717-58a5-4f57-8778-df107ea6e522.png)

![image](https://user-images.githubusercontent.com/24560428/207290287-38afce0c-e353-4fc5-bf7c-a5250c77a84a.png)

**Comment by dexamenos** [comment]
Please generate a new API key, as your key now has become public.

However, we repeat our comment from yesterday: this does not look like an API key from https://exchangeratesapi.io! Which website is your screenshot from?

**Comment by League2EB** [comment]
> Please generate a new API key, as your key now has become public.
> 
> However, we repeat our comment from yesterday: this does not look like an API key from https://exchangeratesapi.io! Which website is your screenshot from?

my api key is from [https://apilayer.com/](https://apilayer.com/)

because , when i tap GET API KEY Button , the website will jump to apolayer.com


![image](https://user-images.githubusercontent.com/24560428/207691744-943f84e3-3246-4c6c-978e-2fe2e8244eb9.png)

**Comment by dexamenos** [comment]
Okay, I see. They obviously changed their site and now forward you to https://apilayer.com, which uses a different API. 

Please try to use the link below and register for the free plan, let's see if this gives you a working API key → https://manage.exchangeratesapi.io/signup/free

**Comment by League2EB** [comment]
i got new error !

```
(
    [error] => Array
        (
            [code] => base_currency_access_restricted
            [message] => An unexpected error ocurred. [Technical Support: support@apilayer.com]
        )

)
```

![image](https://user-images.githubusercontent.com/24560428/207748743-0e58a9aa-4655-41db-b3b4-cafd3831d67f.png)

**Comment by dexamenos** [comment]
We are sorry, you seem to be out of luck. Nevertheless, we can confirm your error.

– first, it seems you know have a working API key for https://exchangeratesapi.io, that is good

– however, they not only seem to have removed the direct possibility to sign up with them, they also **do not** allow other currencies than EUR as the base currency

My suggestion would be to go with one of the other APIs we recommend, https://free.currencyconverterapi.com/free-api-key works as of today

**Comment by League2EB** [comment]
currencyconverterapi free key user is down .... 🥴

![image](https://user-images.githubusercontent.com/24560428/207834689-59f48a8a-ad09-4239-b0f4-34264e17572f.png)

**Comment by dexamenos** [comment]
I have seen that, too. However, it is working for me (with free plan).

<img width="764" alt="image" src="https://user-images.githubusercontent.com/33360918/207835187-367491bc-a250-4c6c-b6ff-f3b26a4f909c.png">

But you are right, this service sometime is down for an hour or two and then back up again.
