### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by andrehofmeyr** [littlebrighter/alfred--ultimate-currency-converter#9]
Hi

I hope you're well.  

I've been very keen to try your currency converter, but I keep getting a JSON error when I try to run the workflow:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/66821142/213467179-214a267c-28d5-4892-8ae4-41ef37825741.png">

Here is the full output from the Debugger:
<?xml version="1.0"?>
<items><item uid="none" arg="1.0797" valid="yes"><title>1.00 EUR &#x2192; 1.08 USD</title><subtitle>Euro &#x1F1EA;&#x1F1FA; &#x2192; United States Dollar &#x1F1FA;&#x1F1F8;</subtitle><icon>icon.png</icon></item></items>
[16:22:09.013] Ultimate Currency Converter[Script Filter] Queuing argument ''
[16:22:09.167] Ultimate Currency Converter[Script Filter] Script with argv '(null)' finished
[16:22:09.171] STDERR: Ultimate Currency Converter[Script Filter] PHP Deprecated:  Creation of dynamic property e4WorkflowDoConvert::$app is deprecated in /Users/andrehofmeyr/Dropbox/Documents/Important/Alfred/Alfred.alfredpreferences/workflows/user.workflow.5C092AB3-9441-4561-A6CD-A24D9E477186/e4WorkflowApp.php on line 315
Array
(
    [base_currency_code] => EUR
    [base_currency_name] => Euro
    [amount] => 1.0000
    [updated_date] => 2023-01-19
    [rates] => Array
        (
            [USD] => Array
                (
                    [currency_name] => United States dollar
                    [rate] => 1.0797
                    [rate_for_amount] => 1.0797
                )

        )

    [status] => success
)
[16:22:09.186] Ultimate Currency Converter[Script Filter] Deprecated: Creation of dynamic property e4WorkflowDoConvert::$app is deprecated in /Users/andrehofmeyr/Dropbox/Documents/Important/Alfred/Alfred.alfredpreferences/workflows/user.workflow.5C092AB3-9441-4561-A6CD-A24D9E477186/e4WorkflowApp.php on line 315
<?xml version="1.0"?>
<items><item uid="none" arg="1.0797" valid="yes"><title>1.00 EUR &#x2192; 1.08 USD</title><subtitle>Euro &#x1F1EA;&#x1F1FA; &#x2192; United States Dollar &#x1F1FA;&#x1F1F8;</subtitle><icon>icon.png</icon></item></items>
[16:22:09.189] ERROR: Ultimate Currency Converter[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Deprecated: Creation of dynamic property e4WorkflowDoConvert::$app is deprecated in /Users/andrehofmeyr/Dropbox/Documents/Important/Alfred/Alfred.alfredpreferences/workflows/user.workflow.5C092AB3-9441-4561-A6CD-A24D9E477186/e4WorkflowApp.php on line 315
<?xml version="1.0"?>
<items><item uid="none" arg="1.0797" valid="yes"><title>1.00 EUR &#x2192; 1.08 USD</title><subtitle>Euro &#x1F1EA;&#x1F1FA; &#x2192; United States Dollar &#x1F1FA;&#x1F1F8;</subtitle><icon>icon.png</icon></item></items>
[16:22:15.776] Logging Stopped.

I hope this helps, and sorry to bother you.

**Comment by dexamenos** [comment]
Hello @andrehofmeyr, 
that looks like something I have not yet come across.
Could you be so kind and share: macOS version, Alfred version and PHP version (how installed? homebrew?).
I will try to recreate the situation.
Thanks

**Comment by andrehofmeyr** [comment]
Thanks for your very quick response, @dexamenos 

I'm using Mac OS Ventura (13.1), the latest version of Alfred (5.0.6), and I installed PHP via homebrew.

I thought one potential issue, although I doubt this could be the case, is that I store my Alfred preferences in Dropbox.

Cheers,
Andre

**Comment by dexamenos** [comment]
Dropbox shouldn't be an issue (but who knows).
PHP version number, please (`php --version` in Terminal).
And: which service/API are you using?
I will then just recreate that setup and check – on my machine, everything is working right now

**Comment by andrehofmeyr** [comment]
PHP 8.2.1

I'm using https://getgeoapi.com

Thanks again for the quick response

**Comment by dexamenos** [comment]
Hey, I have just published a new release (v1.13.0) which hopefully repairs things. 
You can get it from [here](https://github.com/littlebrighter/alfred--ultimate-currency-converter/releases/tag/v1.13.0) or just open UCC tomorrow and the workflow will point you to the new release.

Please let us know if it solves your problems.
